# Generated by Django 5.0.3 on 2024-05-20 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=255)),
                ('telepon', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.CharField(max_length=255)),
                ('telepon', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_daftar', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppdb_app.sekolah')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppdb_app.siswa')),
            ],
        ),
    ]
